x=float(input("Digite el primer número: "))
y=float(input("Digite el segundo número: "))
print("La suma es: ", x+y)
print("La resta es: ", x-y)
print("La multiplicación es: ",x*y)
print("La división es: ",x/y)